keys:
  - &age_generic age1ztv862t6qd64a0d6df6ydukqygsuw8wnqdjzwmycxgr6vvcyachs2tjxvt
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *age_generic

