local vscode = require("vscode")

vim.keymap.set("n", "<leader>:", function()
  vscode.action("workbench.action.showCommands")
end)

vim.keymap.set("n", "<leader>e", function()
  vscode.action("workbench.files.action.focusFilesExplorer")
end)
vim.keymap.set("n", "<leader>wl", function()
  vscode.call("workbench.action.focusRightGroup")
end)
vim.keymap.set("n", "<leader>wh", function()
  vscode.call("workbench.action.focusLeftGroup")
end)
vim.keymap.set("n", "<leader>wk", function()
  vscode.call("workbench.action.focusAboveGroup")
end)
vim.keymap.set("n", "<leader>wj", function()
  vscode.call("workbench.action.focusBelowGroup")
end)
vim.keymap.set("n", "<leader>gg", function()
  vscode.call("workbench.scm.focus")
end)

vim.keymap.set("n", "<leader>,", function()
  vscode.action("workbench.action.showAllEditors")
end)

